site_name: Cobanov
repo_url: https://github.com/cobanov/
repo_name: "Visit my GitHub"
site_author: "Mert Cobanov"
edit_uri: ""

nav:
  - Blog:
      - "index.md"
      - "Helper one-liners": "helpers.md"
      - "New Macbook Installation": "new-macbook.md"
      - "Cypherpunk Manifesto": "cyberpunk.md"
      - 'Doing Python Configuration Right': 'python-conf.md'
      - 'Windows WSL Activate SSH': 'windows-wsl-ssh.md'
      - 'OpenPose': 'openpose.md'
      - 'NeRF': 'nerf.md'

  - Portfolio:
      - "portfolio.md"
  - About:
      - "about.md"
  - diffusion-book:
    - What is Latent Diffusion: ldm.md
    - Samplers: samplers.md
    - Prompting: prompting.md
    - Blender Depthmap: blender-depthmap.md
    - Training LDM: training-ldm.md
    - Fine Tuning: fine-tuning.md
    - Dream Booth: dream-booth.md
    - Tools & Blogs and Useful Links: tools.md

theme: readthedocs
#   icon:
#     repo: fontawesome/brands/github
#   name: material
#   language: tr
#   features:
#     - navigation.tabs
#     - navigation.tabs.sticky
#     - navigation.top

#   palette:
#     primary: black
#     accent: orange
#   font:
#     text: Open Sans
#     code: Red Hat Mono

#   nav_style: dark
#   highlightjs: true
#   hljs_languages:
#     - yaml
#     - python

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences

# extra:
#   social:
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/cobanov
#     - icon: fontawesome/brands/youtube
#       link: https://youtube.com/@mertcobanov
#     - icon: fontawesome/brands/instagram
#       link: https://instagram.com/mertcobanov
